// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-jsIAeIodmSCysXlb3otHFAla8EtgqpM',
    appId: '1:37859370160:web:52489a2c7de0b7a55e0775',
    messagingSenderId: '37859370160',
    projectId: 'homeservice-fbbc9',
    authDomain: 'homeservice-fbbc9.firebaseapp.com',
    storageBucket: 'homeservice-fbbc9.appspot.com',
    measurementId: 'G-0EH54LG2X3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiQUfSw4UbKMUvGx5R3ST9dzJ8TjHvN1U',
    appId: '1:37859370160:android:4934b9fd5f016a3a5e0775',
    messagingSenderId: '37859370160',
    projectId: 'homeservice-fbbc9',
    storageBucket: 'homeservice-fbbc9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2jKnlP2-v8qhx4SwRuxXdF9XVHdFyhjc',
    appId: '1:37859370160:ios:c261ba4a0596d97f5e0775',
    messagingSenderId: '37859370160',
    projectId: 'homeservice-fbbc9',
    storageBucket: 'homeservice-fbbc9.appspot.com',
    iosClientId: '37859370160-6ichoqftpk99uotd8r7aln4kjmvme75n.apps.googleusercontent.com',
    iosBundleId: 'io.initappz.homeservice.user',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2jKnlP2-v8qhx4SwRuxXdF9XVHdFyhjc',
    appId: '1:37859370160:ios:aaf040f3dbe53a965e0775',
    messagingSenderId: '37859370160',
    projectId: 'homeservice-fbbc9',
    storageBucket: 'homeservice-fbbc9.appspot.com',
    iosClientId: '37859370160-mcfnf0fcsubkvtfm1qi0rp924h43hhh2.apps.googleusercontent.com',
    iosBundleId: 'com.example.homeservice',
  );
}
